export const USER_LOADING = 'USER_LOADING'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const UPDATE_SUCCESS = 'UPDATE_SUCCESS'
export const UPDATE_FAILED = 'UPDATE_FAILED'

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILED = 'REGISTER_FAILED'

export const GET_ERRORS = 'GET_ERRORS'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const YOU_BUY_ETHEREUM = 'YOU_BUY_ETHEREUM'
export const CAPITAL_DATA = 'CAPITAL_DATA'

export const GET_USER = 'GET_USER'

export const PROFIT_ADDED = 'PROFIT_ADDED'




